# Generated by Django 4.2.6 on 2023-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_close_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png/jpg', upload_to='profile_images/'),
        ),
    ]
