# Generated by Django 4.2.6 on 2023-10-15 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test_pass_percentage_alter_test_end_data_checktest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktest',
            old_name='answerd',
            new_name='true_answers',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 9, 13, 45, 445205, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
