# Generated by Django 4.2.6 on 2023-10-18 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_answerd_checktest_true_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checktests', to='main.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 13, 44, 57, 775957, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
