# Generated by Django 4.2.6 on 2023-10-19 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_checktest_test_alter_test_end_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 8, 44, 1, 850856, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
